version: '3.8'

services:
  shopee-monitor-qa:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopee-monitor:qa
    container_name: shopee-monitor-qa
    restart: unless-stopped
    ports:
      - ":3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT_ID=
      - STOCK_CHECK_CRON=
    volumes:
      - ./data/qa:/app/data
